#!/usr/bin/env bash
# Deployment logic, written as pure functions over their arguments.
#
# Nothing here opens an SSH connection or touches Docker. That is deliberate:
# it is what lets the unit suite exercise the real colour selection, port
# mapping and nginx rendering without an EC2 instance, a registry, or a network.
# The orchestration that does need those lives in deploy.sh.
#
# Targets bash 3.2 — established in Linux-Server-Hardening, because macOS still
# ships it and contributors have to be able to run the tests.

# Blue/green: the colour currently serving traffic is read from the host, and
# the deployment always goes to the other one. Nothing is ever deployed over the
# container that is live.
next_color() {
    case "${1:-}" in
        blue) printf 'green' ;;
        green) printf 'blue' ;;
        # No colour recorded means nothing has been deployed yet. Starting at
        # blue keeps the very first deploy identical to every later one rather
        # than being a special case.
        *) printf 'blue' ;;
    esac
}

# Each colour owns a fixed port. Fixed rather than allocated, so a half-finished
# deploy leaves the host in a state a human can reason about.
port_for_color() {
    case "${1:-}" in
        blue) printf '3001' ;;
        green) printf '3002' ;;
        *) return 1 ;;
    esac
}

container_name() {
    local app="${1:?app name required}" color="${2:?color required}"
    printf '%s-%s' "$app" "$color"
}

# Images are addressed by immutable tag, never by :latest. A deploy must be able
# to say exactly which build is running, and a rollback must be able to name the
# build it is returning to — neither is possible if the tag moves.
image_ref() {
    local registry="${1:?registry required}" repo="${2:?repo required}" tag="${3:?tag required}"
    if [[ "$tag" == "latest" ]]; then
        printf 'refusing to deploy a mutable tag: latest\n' >&2
        return 1
    fi
    printf '%s/%s:%s' "$registry" "$repo" "$tag"
}

# nginx upstream pointing at whichever colour should receive traffic. Written to
# a temp file and moved into place atomically by the caller, so a reload can
# never read a half-written file.
render_upstream() {
    local color="${1:?color required}" port
    port="$(port_for_color "$color")" || return 1
    cat <<EOF
# Generated by deploy.sh — do not edit by hand.
# Active colour: ${color}
upstream app {
    server 127.0.0.1:${port};
    keepalive 16;
}
EOF
}

# Validates what the caller believes about a health response. Kept separate from
# the polling loop so both the success and failure paths are testable without a
# server.
health_is_ok() {
    local body="${1:-}" expected_version="${2:-}"
    [[ -n "$body" ]] || return 1
    printf '%s' "$body" | grep -q '"status":"ok"' || return 1
    # A deploy that reports healthy while running the previous build has not
    # deployed. Checking the version is what makes verification real.
    if [[ -n "$expected_version" ]]; then
        printf '%s' "$body" | grep -q "\"version\":\"${expected_version}\"" || return 1
    fi
    return 0
}

# Remote commands are assembled here so quoting is in one place rather than
# scattered through the orchestration.
remote_docker_run() {
    local image="${1:?}" name="${2:?}" port="${3:?}" color="${4:?}" version="${5:?}"
    cat <<EOF
docker rm -f ${name} >/dev/null 2>&1 || true
docker run -d \
  --name ${name} \
  --restart unless-stopped \
  --read-only --tmpfs /tmp \
  --security-opt no-new-privileges:true \
  --memory 256m --pids-limit 128 \
  -p 127.0.0.1:${port}:3000 \
  -e APP_VERSION=${version} \
  -e DEPLOY_COLOR=${color} \
  ${image}
EOF
}
